name: PHP

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - uses: actions/checkout@v4
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with:
          args: --no-scripts
          php_version: "8.4"
          php_extensions: dom libxml
      - name: Run PHPStan
        run: ./vendor/bin/phpstan
      - name: Run ECS
        run: ./vendor/bin/ecs
      - name: Run Rector
        run: ./vendor/bin/rector --dry-run
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
